### ISSUE TITLE
Fails to build with fdsdk 25.08

### ISSUE THREAD

**Issue by bbhtt** [refi64/zypak#44]
```
src/base/enum_util.h: In copy constructor ‘zypak::enum_util_detail::FlagOrBool<T>::FlagOrBool(const zypak::enum_util_detail::FlagOrBool<T>&)’:
src/base/enum_util.h:23:57: error: ‘const class zypak::enum_util_detail::FlagOrBool<T>’ has no member named ‘value’; did you mean ‘value_’? [-Wtemplate-body]
   23 |   FlagOrBool(const FlagOrBool<T>& other) : value_(other.value) {}
      |                                                         ^~~~~
      |                                                         value_
Makefile:67: warning: pattern recipe did not update peer target '/preload_host/sandbox_suid.d'.
g++ -DZYPAK_RELEASE="\"v2024.01.17\"" -fstack-protector-all -fstack-clash-protection -Wall -Werror -std=c++20 -g -pthread -Inickle -Isrc  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include    -fPIC -MD -c -o build/obj/preload_host_spawn_strategy/bus_safe_fork.o src/preload/host/spawn_strategy/bus_safe_fork.cc
Makefile:75: warning: pattern recipe did not update peer target '/preload_host_mimic_strategy/initialize.d'.
g++ -DZYPAK_RELEASE="\"v2024.01.17\"" -fstack-protector-all -fstack-clash-protection -Wall -Werror -std=c++20 -g -pthread -Inickle -Isrc  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include    -fPIC -MD -c -o build/obj/preload_host_spawn_strategy/initialize.o src/preload/host/spawn_strategy/initialize.cc
Makefile:42: warning: pattern recipe did not update peer target '/base/env.d'.
g++ -DZYPAK_RELEASE="\"v2024.01.17\"" -fstack-protector-all -fstack-clash-protection -Wall -Werror -std=c++20 -g -pthread -Inickle -Isrc  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include    -fPIC -MD -c -o build/obj/preload_host_spawn_strategy/process_override.o src/preload/host/spawn_strategy/process_override.cc
Makefile:42: warning: pattern recipe did not update peer target '/base/debug.d'.
g++ -DZYPAK_RELEASE="\"v2024.01.17\"" -fstack-protector-all -fstack-clash-protection -Wall -Werror -std=c++20 -g -pthread -Inickle -Isrc  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include    -fPIC -MD -c -o build/obj/preload_host_spawn_strategy/spawn_launcher_delegate.o src/preload/host/spawn_strategy/spawn_launcher_delegate.cc
Makefile:67: warning: pattern recipe did not update peer target '/preload_host/exec_zypak_sandbox.d'.
g++ -DZYPAK_RELEASE="\"v2024.01.17\"" -fstack-protector-all -fstack-clash-protection -Wall -Werror -std=c++20 -g -pthread -Inickle -Isrc  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include    -fPIC -MD -c -o build/obj/preload_host_spawn_strategy/supervisor.o src/preload/host/spawn_strategy/supervisor.cc
Makefile:67: warning: pattern recipe did not update peer target '/preload_host/sandbox_path.d'.
g++ -DZYPAK_RELEASE="\"v2024.01.17\"" -fstack-protector-all -fstack-clash-protection -Wall -Werror -std=c++20 -g -pthread -Inickle -Isrc  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -fPIC -MD -c -o build/obj/dbus/bus.o src/dbus/bus.cc
Makefile:42: warning: pattern recipe did not update peer target '/base/strace.d'.
g++ -DZYPAK_RELEASE="\"v2024.01.17\"" -fstack-protector-all -fstack-clash-protection -Wall -Werror -std=c++20 -g -pthread -Inickle -Isrc  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -fPIC -MD -c -o build/obj/dbus/bus_error.o src/dbus/bus_error.cc
Makefile:42: warning: pattern recipe did not update peer target '/base/debug_internal/log_stream.d'.
g++ -DZYPAK_RELEASE="\"v2024.01.17\"" -fstack-protector-all -fstack-clash-protection -Wall -Werror -std=c++20 -g -pthread -Inickle -Isrc  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -fPIC -MD -c -o build/obj/dbus/bus_readable_message.o src/dbus/bus_readable_message.cc
Makefile:42: warning: pattern recipe did not update peer target '/base/fd_map.d'.
g++ -DZYPAK_RELEASE="\"v2024.01.17\"" -fstack-protector-all -fstack-clash-protection -Wall -Werror -std=c++20 -g -pthread -Inickle -Isrc  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -fPIC -MD -c -o build/obj/dbus/bus_writable_message.o src/dbus/bus_writable_message.cc
Makefile:42: warning: pattern recipe did not update peer target '/base/socket.d'.
g++ -DZYPAK_RELEASE="\"v2024.01.17\"" -fstack-protector-all -fstack-clash-protection -Wall -Werror -std=c++20 -g -pthread -Inickle -Isrc  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -fPIC -MD -c -o build/obj/dbus/flatpak_portal_proxy.o src/dbus/flatpak_portal_proxy.cc
make: *** [Makefile:42: build/obj/base/launcher.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/base/launcher.h:10,
                 from src/preload/host/spawn_strategy/spawn_launcher_delegate.h:8,
                 from src/preload/host/spawn_strategy/spawn_launcher_delegate.cc:5:
src/base/enum_util.h: In copy constructor ‘zypak::enum_util_detail::FlagOrBool<T>::FlagOrBool(const zypak::enum_util_detail::FlagOrBool<T>&)’:
src/base/enum_util.h:23:57: error: ‘const class zypak::enum_util_detail::FlagOrBool<T>’ has no member named ‘value’; did you mean ‘value_’? [-Wtemplate-body]
   23 |   FlagOrBool(const FlagOrBool<T>& other) : value_(other.value) {}
      |                                                         ^~~~~
      |                                                         value_
Makefile:42: warning: pattern recipe did not update peer target '/base/evloop.d'.
Makefile:55: warning: pattern recipe did not update peer target '/dbus/bus_error.d'.
In file included from src/dbus/flatpak_portal_proxy.h:13,
                 from src/preload/host/spawn_strategy/supervisor.h:18,
                 from src/preload/host/spawn_strategy/initialize.cc:17:
src/base/enum_util.h: In copy constructor ‘zypak::enum_util_detail::FlagOrBool<T>::FlagOrBool(const zypak::enum_util_detail::FlagOrBool<T>&)’:
src/base/enum_util.h:23:57: error: ‘const class zypak::enum_util_detail::FlagOrBool<T>’ has no member named ‘value’; did you mean ‘value_’? [-Wtemplate-body]
   23 |   FlagOrBool(const FlagOrBool<T>& other) : value_(other.value) {}
      |                                                         ^~~~~
      |                                                         value_
In file included from src/dbus/flatpak_portal_proxy.h:13,
                 from src/dbus/flatpak_portal_proxy.cc:5:
src/base/enum_util.h: In copy constructor ‘zypak::enum_util_detail::FlagOrBool<T>::FlagOrBool(const zypak::enum_util_detail::FlagOrBool<T>&)’:
src/base/enum_util.h:23:57: error: ‘const class zypak::enum_util_detail::FlagOrBool<T>’ has no member named ‘value’; did you mean ‘value_’? [-Wtemplate-body]
   23 |   FlagOrBool(const FlagOrBool<T>& other) : value_(other.value) {}
      |                                                         ^~~~~
      |                                                         value_
Makefile:55: warning: pattern recipe did not update peer target '/dbus/bus_writable_message.d'.
In file included from src/dbus/flatpak_portal_proxy.h:13,
                 from src/preload/host/spawn_strategy/supervisor.h:18,
                 from src/preload/host/spawn_strategy/process_override.cc:12:
src/base/enum_util.h: In copy constructor ‘zypak::enum_util_detail::FlagOrBool<T>::FlagOrBool(const zypak::enum_util_detail::FlagOrBool<T>&)’:
src/base/enum_util.h:23:57: error: ‘const class zypak::enum_util_detail::FlagOrBool<T>’ has no member named ‘value’; did you mean ‘value_’? [-Wtemplate-body]
   23 |   FlagOrBool(const FlagOrBool<T>& other) : value_(other.value) {}
      |                                                         ^~~~~
      |                                                         value_
Makefile:55: warning: pattern recipe did not update peer target '/dbus/bus_readable_message.d'.
Makefile:87: warning: pattern recipe did not update peer target '/preload_host_spawn_strategy/bus_safe_fork.d'.
make: *** [Makefile:87: build/obj/preload_host_spawn_strategy/initialize.o] Error 1
In file included from src/dbus/flatpak_portal_proxy.h:13,
                 from src/preload/host/spawn_strategy/supervisor.h:18,
                 from src/preload/host/spawn_strategy/supervisor.cc:6:
src/base/enum_util.h: In copy constructor ‘zypak::enum_util_detail::FlagOrBool<T>::FlagOrBool(const zypak::enum_util_detail::FlagOrBool<T>&)’:
src/base/enum_util.h:23:57: error: ‘const class zypak::enum_util_detail::FlagOrBool<T>’ has no member named ‘value’; did you mean ‘value_’? [-Wtemplate-body]
   23 |   FlagOrBool(const FlagOrBool<T>& other) : value_(other.value) {}
      |                                                         ^~~~~
      |                                                         value_

```

**Comment by refi64** [comment]
appreciate the reminder as to why I no longer use C++

**Comment by refi64** [comment]
Fix is included in https://github.com/refi64/zypak/releases/tag/v2025.09.
